# Generated by Django 4.0.5 on 2022-06-08 08:03

import autoslug.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=30)),
                ('descrizione', models.TextField(max_length=200)),
                ('tipologia', models.CharField(choices=[('B', 'Bicicletta'), ('A', 'Accessori')], max_length=15)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='titolo', unique=True)),
                ('immagine', models.ImageField(upload_to='')),
                ('condizione', models.CharField(choices=[('N', 'Nuovo'), ('U', 'Usato')], max_length=15)),
                ('categoria', models.CharField(choices=[('A', 'Accessori'), ('B', 'Bambino'), ('C', 'Città'), ('D', 'Corsa'), ('E', 'Elettriche'), ('M', 'Mountain')], max_length=15)),
                ('genere', models.CharField(choices=[('D', 'Donna'), ('U', 'Uomo'), ('B', 'Bambino')], max_length=15)),
                ('ordinato', models.BooleanField(default=False)),
                ('prezzo', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('venditore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Articoli',
            },
        ),
    ]
