# Generated by Django 4.0.4 on 2022-06-09 08:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bike', '0002_order_shippingaddress_payment_orderitem_order_items_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Ordini'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name_plural': 'Pagamenti'},
        ),
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name_plural': 'Indirizzi'},
        ),
        migrations.CreateModel(
            name='RecommendedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_item', models.PositiveIntegerField(default=0)),
                ('condizioneN', models.PositiveIntegerField(default=0)),
                ('condizioneU', models.PositiveIntegerField(default=0)),
                ('prezzo', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('sum_prezzo', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Articoli Consigliati',
            },
        ),
    ]
