# Generated by Django 4.0.4 on 2022-06-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0003_alter_order_options_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
    ]
